### ISSUE TITLE
Problems with Korean’s translation on Weblate

### ISSUE THREAD

**Issue by DDinghoya** [Slicer/SlicerLanguagePacks#13] opened 2022-09-17 05:07 UTC
Dear,

The above issue has been posted to the 3D Splicer community -> [Link](https://discourse.slicer.org/t/problems-with-koreans-translation-on-weblate/25296)

Basically the Korean translation was 100% completed on weblate, and there were two problems.

1. Korean translation was made, but some items (Menu, Settings, etc.) are not reflected as belows sample pictures;

* Sample_Menu *
![sample_menu](https://user-images.githubusercontent.com/19677686/190841436-f75c9ef3-af5b-48c0-9b8c-ee2bdab43d53.png)

* Sample_settings *
![sample_settings](https://user-images.githubusercontent.com/19677686/190841386-fa72baf3-1db0-47f6-bd19-ef6e3aab4f9b.png)

Even if I downloaded the language pack from github and applied it manually, it was not reflected.

2. Some HTML tags disappear after saving the translation on Weblatea as below;

* Sample _HTML *
![sample_html](https://user-images.githubusercontent.com/19677686/190841452-7a42ccc6-d629-48d9-8dcd-ca3fc0f850d0.png)

I think the problem arises when using a 2 byte character set.

It is hoped that the cause of the problem and improvement will be addressed through this post. :)

Best regards.

**Comment by mhdiop** [comment] 2022-09-21 21:55
Dear @DDinghoya,

Thank you for your exhaustive report, we really appreciate it !

Regarding your first remark, it should be noted that not all strings present in the Slicer GUI are currently listed on [Weblate](https://hosted.weblate.org/engage/3d-slicer/), the translation platform. The remaining strings mainly concern:
- strings which should be marked as translatable and which are not (both in Python and C++ codes)
- strings that are already marked but are not extracted yet (mainly in Slicer's Python code)

As @pieper mentioned in the [linked post](https://discourse.slicer.org/t/problems-with-koreans-translation-on-weblate/25296/2), there is an [ongoing project](https://chanzuckerberg.com/eoss/proposals/3d-slicer-in-my-language-internationalization-and-usability-improvements/) that addresses this issue and some of their work in progress may interest you.
- For translatable strings present in Python codes, a [string extractor](https://github.com/Slicer/sliceri18n) has been developed.
- For translatable strings that are not tagged yet, [string marking tools](https://github.com/mhdiop/slicer-tools) are also proposed.

We are currently working on their integration into the internationalization process and should have convincing results shortly. Thus, missing strings should be available for translation.

For your second point, we will investigate it further to see what's causing it.
@lassoan, @pieper, @Adama-WADE are key resources that may help too.

Thank you again for your interests in this project.

Best regards.

**Comment by lassoan** [comment] 2022-10-19 15:18
Some of this issues are caused by `safe-html` setting in Weblate that attempted to sanitize translated text of HTML content. This is now disabled (see https://github.com/Slicer/SlicerLanguagePacks/issues/14) and so it should be possible to translate text that contain html tags and special characters.

Text that does not appear in translations are generated dynamically from code and they are not marked as translatable. @mhdiop is working on exposing all these strings. This is tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/12.

Since these issues are already tracked in other issues, I'm closing this issue now.

**Closed by lassoan** 2022-10-19 15:18 UTC
